//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHang.Context
{
    using System;
    using System.Collections.Generic;

    public partial class OrderDetail
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int ProductId { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> idUser { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<double> Pay { get; set; }

        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
        public virtual Order Order { get; set; }
    }

    public partial class OrderDetailDTO
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public Nullable<System.DateTime> CreatedOnUtc { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductAvatar { get; set; }
        public Nullable<double> ProductPrice { get; set; }
        public Nullable<double> SumPrice { get; set; }
        public int Quantity { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<double> Pay { get; set; }
        public string PayToWord { get; set; }
    }
}
